### PR TITLE
Laravel 8 support

### PR DESCRIPTION
**Pull request by royduin**

### CODE REVIEW

**Review by alphaolomi — APPROVED** [review]

**Comment by alphaolomi** [comment]
Much Thanks to @royduin

**Comment by royduin** [comment]
Ping @mpociot

**Comment by eduardocruz** [comment]
@mpociot Ping

**Comment by yormy** [comment]
+1

**Comment by kerimkuscu** [comment]
@mpociot ping

**Comment by mpociot** [comment]
Thank you!

**Pull request merged**
